{
    "children": null,
    "attachments": null,
    "relations": [
        {
            "id": 220,
            "issue_id": 823,
            "issue_to_id": 822,
            "relation_type": "relates",
            "delay": null
        },
        {
            "id": 233,
            "issue_id": 822,
            "issue_to_id": 330,
            "relation_type": "relates",
            "delay": null
        }
    ],
    "changesets": [],
    "journals": [
        {
            "id": 4664,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "",
            "created_on": "2015-02-23T19:04:47Z",
            "details": [
                {
                    "property": "relation",
                    "name": "relates",
                    "new_value": "823"
                }
            ]
        },
        {
            "id": 4679,
            "user": {
                "id": 35,
                "name": "Dragonji"
            },
            "notes": "",
            "created_on": "2015-02-27T15:44:32Z",
            "details": [
                {
                    "property": "attr",
                    "name": "priority_id",
                    "old_value": "4",
                    "new_value": "5"
                }
            ]
        },
        {
            "id": 4736,
            "user": {
                "id": 140,
                "name": "Spyhawk"
            },
            "notes": "Setting sv_wwwDlDisconnected to \"1\" seems to be a working workaround.",
            "created_on": "2015-03-08T21:07:47Z",
            "details": []
        },
        {
            "id": 4835,
            "user": {
                "id": 140,
                "name": "Spyhawk"
            },
            "notes": "",
            "created_on": "2015-03-21T09:08:12Z",
            "details": [
                {
                    "property": "relation",
                    "name": "relates",
                    "new_value": "330"
                }
            ]
        },
        {
            "id": 4914,
            "user": {
                "id": 424,
                "name": "Zecklar"
            },
            "notes": "I didn't manage to reproduce this problem. Anyone who manages to reproduce, please feel free to share the details. I just wanna to if this problem still exists...",
            "created_on": "2015-04-11T20:08:16Z",
            "details": []
        },
        {
            "id": 5005,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "",
            "created_on": "2015-07-24T05:43:37Z",
            "details": [
                {
                    "property": "attr",
                    "name": "status_id",
                    "old_value": "1",
                    "new_value": "4"
                }
            ]
        },
        {
            "id": 5010,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "Can't reproduce.",
            "created_on": "2015-07-24T07:23:06Z",
            "details": []
        },
        {
            "id": 5116,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "",
            "created_on": "2015-08-08T20:56:19Z",
            "details": [
                {
                    "property": "attr",
                    "name": "fixed_version_id",
                    "old_value": "17",
                    "new_value": "8"
                }
            ]
        },
        {
            "id": 5564,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "",
            "created_on": "2015-12-05T18:33:15Z",
            "details": [
                {
                    "property": "attr",
                    "name": "status_id",
                    "old_value": "4",
                    "new_value": "5"
                },
                {
                    "property": "attr",
                    "name": "fixed_version_id",
                    "old_value": "8",
                    "new_value": "2"
                },
                {
                    "property": "attr",
                    "name": "done_ratio",
                    "old_value": "0",
                    "new_value": "100"
                }
            ]
        }
    ],
    "watchers": [
        {
            "id": 9,
            "name": "Mateos"
        },
        {
            "id": 405,
            "name": "Latch"
        }
    ],
    "time_entries": null,
    "id": 822,
    "project": {
        "id": 1,
        "name": "ET: Legacy Development"
    },
    "tracker": {
        "id": 1,
        "name": "Bug"
    },
    "status": {
        "id": 5,
        "name": "Fixed"
    },
    "priority": {
        "id": 5,
        "name": "High"
    },
    "author": {
        "id": 140,
        "name": "Spyhawk"
    },
    "assigned_to": {
        "id": 44,
        "name": "Jacker"
    },
    "category": {
        "id": 12,
        "name": "General"
    },
    "fixed_version": {
        "id": 2,
        "name": "2.75"
    },
    "subject": "Client redirected to sv_wwwFallbackURL while files are still downloading",
    "description": "This is related to the new downloading code. See http://dev.etlegacy.com/boards/3/topics/1519.\r\n\r\nTalked to Jacker a few days ago, this issue was \"kinda expected\" ;)",
    "start_date": "2015-02-23",
    "done_ratio": 100,
    "custom_fields": [
        {
            "id": 1,
            "name": "OS",
            "value": ""
        },
        {
            "id": 2,
            "name": "Arch",
            "value": ""
        }
    ],
    "created_on": "2015-02-23T17:41:01Z",
    "updated_on": "2015-12-05T18:33:15Z",
    "closed_on": "2015-12-05T18:33:15Z"
}